version: '3'
services:
  relying_party:
    build: ./relying_party
    ports:
      - 80:80
    depends_on:
      - keycloak
      - redis
  keycloak:
    build: ./keycloak
    ports:
      - 8080:8080
    environment:
#      KEYCLOAK_USER: admin
#      KEYCLOAK_PASSWORD: password
      PROXY_ADDRESS_FORWARDING: "true"
  redis:
    image: "redis:alpine"
    command: redis-server --appendonly yes --requirepass foobar